name: 'Comment to trigger action'
description: 'Comment to trigeger a repository dispatch'
author: 'stewart42'
inputs:
  token:
    description: 'A GitHub Access Token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
