name: 'Comment to trigger workflow'
description: 'Comment to trigger a repository dispatch'
author: 'stewart42'
inputs:
  GITHUB_TOKEN:
    description: 'A gitHub access token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
