name: 'comment-bot'

on:
  issue_comment:
    types: created

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          event-type: build-test
