name: 'format'

on:
  repository_dispatch:
    types: [format]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.head_ref }}
      - run: |
          npm install
      - run: |
          npm run format
