name: 'build-test'
on:
  repository_dispatch:
    types: [build-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.head_ref }}
      - run: echo ${{ github.event.client_payload.head_ref :: github.event.client_payload.head_sha }}
      - run: echo ${{ github.event.client_payload.base_ref :: github.event.client_payload.base_sha }}
      - run: |
          npm install
      - run: |
          npm run all
